package InterfacesGraficas;


import Gerenciador.GerenciadorAdm;
import Modelo.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 * Classe responsável pela interface gráfica para cadastro e atualização de pacientes.
 * Permite cadastrar um novo paciente ou atualizar um paciente existente, incluindo a seleção de informações pessoais e de convênio.
 * 
 * @author matheus
 */
public class CadAutPaciente extends javax.swing.JFrame {
    
    private GerenciadorAdm gerenciadorAdm;
    private EntityManager em;
    private Secretaria secretaria = null;
    private Paciente paciente;
    private String Cad_Atu = "Cadastrar";
    
    /**
     * Construtor da classe.
     * Inicializa a interface gráfica e configura o nome da secretaria.
     * 
     * @param secretaria a secretaria associada ao paciente
     * @param gerenciadorAdm o gerenciador de administração responsável pelas operações de CRUD
     * @param em o EntityManager utilizado para interagir com o banco de dados
     */
    public CadAutPaciente(Secretaria secretaria, GerenciadorAdm gerenciadorAdm, EntityManager em) {
        initComponents();
        this.secretaria = secretaria;
        this.gerenciadorAdm = gerenciadorAdm;
        this.em = em;
        lblNomeSecretaria.setText(" " + secretaria.getNome());
        setLocationRelativeTo(null);
    }

    /**
     * Define o paciente que será atualizado e ajusta o texto dos componentes da interface para refletir a operação de atualização.
     * 
     * @param paciente o objeto Paciente que será atualizado
     */
    public void setPaciente(Paciente paciente){
        this.paciente = paciente;
        this.Cad_Atu = "Atualizar Paciente";
        lblSubTitulo.setText(Cad_Atu);
        btn_Cad_Atu.setText("Atualizar");
        this.setTitle("Secretária - Atualizar Paciente");
        setValues();
    }
    
    /**
     * Preenche os campos da interface com os dados do paciente quando a operação é de atualização.
     * Configura os valores dos campos baseados no objeto Paciente fornecido.
     */
    public void setValues(){
        nome.setText(this.paciente.getNome());
        telefone.setText(this.paciente.getTelefone());
        endereco.setText(this.paciente.getEndereco());
        email1.setText(this.paciente.getEmail());
        idade.setText(Integer.toString(this.paciente.getIdade()));
        dataNascimento.setText(this.paciente.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        
        if(this.paciente.getTipoConvenio().equals(Paciente.tipoConvenio.PLANOSAUDE)){
            planoSaude.setSelected(true);
        } else {
            particular.setSelected(true);
        }
        
        if(this.paciente.getSexo().equals("Masculino")){
            masculino.setSelected(true);
        } else {
            feminino.setSelected(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoConvenio = new javax.swing.ButtonGroup();
        sexo = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNomeSecretaria = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblSubTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labell4343 = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JTextField();
        labell4344 = new javax.swing.JLabel();
        planoSaude = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_Cad_Atu = new javax.swing.JButton();
        particular = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretária - Cadastrar Paciente");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Secretaria:");

        lblNomeSecretaria.setBackground(new java.awt.Color(255, 255, 255));
        lblNomeSecretaria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeSecretaria.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeSecretaria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeSecretaria.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuPricipalSecretaria(evt);
            }
        });

        lblSubTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitulo.setText("Cadastrar Paciente");
        lblSubTitulo.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");

        endereco.setBackground(new java.awt.Color(255, 255, 255));
        endereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endereco.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Endereço:");

        email1.setBackground(new java.awt.Color(255, 255, 255));
        email1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        masculino.setBackground(new java.awt.Color(204, 204, 204));
        sexo.add(masculino);
        masculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        masculino.setForeground(new java.awt.Color(0, 0, 0));
        masculino.setText("Masculino");

        feminino.setBackground(new java.awt.Color(204, 204, 204));
        sexo.add(feminino);
        feminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feminino.setForeground(new java.awt.Color(0, 0, 0));
        feminino.setText("Feminino");

        telefone.setBackground(new java.awt.Color(255, 255, 255));
        telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefone.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Telefone:");

        labell4343.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labell4343.setForeground(new java.awt.Color(0, 0, 0));
        labell4343.setText("Data Nascimento (dd/mm/aaaa):");

        dataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        dataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataNascimento.setForeground(new java.awt.Color(0, 0, 0));

        labell4344.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labell4344.setForeground(new java.awt.Color(0, 0, 0));
        labell4344.setText("Sexo:");

        planoSaude.setBackground(new java.awt.Color(204, 204, 204));
        tipoConvenio.add(planoSaude);
        planoSaude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        planoSaude.setForeground(new java.awt.Color(0, 0, 0));
        planoSaude.setText("Plano de Saude");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Idade:");
        jLabel8.setToolTipText("");

        idade.setBackground(new java.awt.Color(255, 255, 255));
        idade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idade.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo Convenio:");
        jLabel9.setToolTipText("");

        btn_Cad_Atu.setBackground(new java.awt.Color(51, 204, 0));
        btn_Cad_Atu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Cad_Atu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cad_Atu.setText("Cadastrar");
        btn_Cad_Atu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cad_AtuActionPerformed(evt);
            }
        });

        particular.setBackground(new java.awt.Color(204, 204, 204));
        tipoConvenio.add(particular);
        particular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        particular.setForeground(new java.awt.Color(0, 0, 0));
        particular.setText("Particular");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                                .addComponent(nome)
                                .addComponent(endereco)
                                .addComponent(email1))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(labell4343)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataNascimento))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(labell4344))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(planoSaude)
                                .addComponent(masculino))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(feminino)
                                .addComponent(particular)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Cad_Atu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefone)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labell4343))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labell4344)
                    .addComponent(masculino)
                    .addComponent(feminino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planoSaude)
                    .addComponent(particular)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Cad_Atu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
/**
     * Cadastra ou atualiza um paciente com base nas informações fornecidas nos campos da interface gráfica.
     * 
     * @param evt o evento de clique do botão
     */
    private void cadAutPaciente(){
        String nome_p, endereco_p, telefone_p, email_p, idade_p, dataNascimento_p, genero_p = null, convenio_p = null;

        nome_p = nome.getText();
        telefone_p = telefone.getText();
        endereco_p = endereco.getText();
        email_p = email1.getText();
        idade_p = idade.getText();
        dataNascimento_p = dataNascimento.getText();
        
        if(planoSaude.isSelected()){
            convenio_p = "PLANOSAUDE";
        } else {
            convenio_p = "PARTICULAR";
        }
        
        if(masculino.isSelected()){
           genero_p = "Masculino";
        } else {
            genero_p = "Feminino";
        }
        
        if(this.paciente == null){
            int dialogResult = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja cadastrar o paciente " + nome_p + "?",
                        "Confirmar Cadastro",
                        JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION){
                this.secretaria.cadastrarPaciente(nome_p, LocalDate.parse(dataNascimento_p, DateTimeFormatter.ofPattern("dd/MM/yyyy")), telefone_p, email_p, endereco_p, convenio_p, Integer.parseInt(idade_p), genero_p);
                MenuSecretariaPaciente menuSecretariaPaciente = new MenuSecretariaPaciente(secretaria, gerenciadorAdm, em);
                menuSecretariaPaciente.setVisible(true);
                this.dispose();
            }
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja atualizar o paciente " + this.paciente.getNome() + "?",
                        "Confirmar Atualização",
                        JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION){
                this.secretaria.atualizarPaciente(this.paciente, nome_p, LocalDate.parse(dataNascimento_p, DateTimeFormatter.ofPattern("dd/MM/yyyy")), telefone_p, email_p, endereco_p, convenio_p, Integer.parseInt(idade_p), genero_p);
                MenuSecretariaPaciente menuSecretariaPaciente = new MenuSecretariaPaciente(secretaria, gerenciadorAdm, em);
                menuSecretariaPaciente.setVisible(true);
                this.dispose();
            }
        }
    }
    
    /**
     * Chama o método {@link #cadAutPaciente} quando o botão é clicado para cadastrar ou atualizar o paciente.
     * 
     * @param evt o evento de clique do botão
     */
    private void btn_Cad_AtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cad_AtuActionPerformed
        cadAutPaciente();
    }//GEN-LAST:event_btn_Cad_AtuActionPerformed

    /**
     * Navega de volta para a janela do menu da secretaria.
     * 
     * @param evt o evento de clique do botão
     */
    private void backMenuPricipalSecretaria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuPricipalSecretaria
        MenuSecretariaPaciente menuSecretariaPaciente = new MenuSecretariaPaciente(secretaria, gerenciadorAdm, em);
        menuSecretariaPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMenuPricipalSecretaria

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cad_Atu;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField endereco;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labell4343;
    private javax.swing.JLabel labell4344;
    private javax.swing.JLabel lblNomeSecretaria;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nome;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton particular;
    private javax.swing.JRadioButton planoSaude;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField telefone;
    private javax.swing.ButtonGroup tipoConvenio;
    // End of variables declaration//GEN-END:variables
}
