/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import Gerenciador.GerenciadorAdm;
import Modelo.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 * Tela de cadastro e atualização de consultas.
 * Esta classe é responsável por permitir o agendamento e atualização de consultas, 
 * incluindo seleção de pacientes, médicos e definição de tipo de consulta.
 * 
 * @author matheus
 */
public class CadAutConsulta extends javax.swing.JFrame {
    private Secretaria secretaria;
    private EntityManager em;
    private GerenciadorAdm gerenciadorAdm;
    private Consulta consulta = null;
    private String Cad_Atu = "Cadastrar";
 
    /**
     * Cria uma nova instância da tela de cadastro e atualização de consultas.
     *
     * @param secretaria A instância da secretaria que gerencia os pacientes e médicos.
     * @param gerenciadorAdm O gerenciador de administração.
     * @param em O EntityManager usado para interações com o banco de dados.
     */
    public CadAutConsulta(Secretaria secretaria, GerenciadorAdm gerenciadorAdm, EntityManager em) {
        initComponents();
        this.secretaria = secretaria;
        this.gerenciadorAdm = gerenciadorAdm;
        this.em = em;
        setMedPac();
        lblNomeSecretaria.setText(" " + secretaria.getNome());
        setLocationRelativeTo(null);
    }
    
    /**
     * Inicializa as listas de médicos e pacientes nos respectivos combo boxes.
     */
    public void setMedPac(){
        paciente_consulta.removeAllItems();
        paciente_consulta.addItem("Selecione um paciente");
        paciente_consulta.setSelectedItem("Selecione um paciente");
        
        for(Paciente paciente : this.secretaria.getAllPacientes()){
            paciente_consulta.addItem(paciente.getNome());
        }
        

        
        medico_consulta.removeAllItems();
        medico_consulta.addItem("Selecione um medico");
        medico_consulta.setSelectedItem("Selecione um medico");
        
        
        for(Medico medico : this.secretaria.listarMedicos()){
            medico_consulta.addItem(medico.getNome());
        }
        
    }
        
    /**
     * Define a consulta a ser editada e atualiza a interface com os detalhes da consulta.
     *
     * @param consulta A consulta a ser editada.
     */
    public void setConsulta(Consulta consulta){
        this.consulta = consulta;
        this.Cad_Atu = "Atualizar Consulta";
        lblSubTitulo.setText(Cad_Atu);
        btn_Register.setText("Atualizar");
        this.setTitle("Secretária - Atualizar consulta");
        setValues();
    }

    /**
     * Preenche os campos da tela com os valores da consulta.
     */
    public void setValues(){
        data_consulta.setText(this.consulta.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        horario_consulta.setText(this.consulta.getHorario().toString());
        

        if(this.consulta.getTipo().equals(Consulta.Tipo.NORMAL)){
            normal.setSelected(true);
        }
        else{
            retorno.setSelected(true);
        }
        
        paciente_consulta.removeAllItems();
        
        paciente_consulta.addItem(this.consulta.getPaciente().getNome());
        paciente_consulta.setSelectedItem(this.consulta.getPaciente().getNome());

        
        medico_consulta.removeAllItems();
        
        for(Medico medico : this.secretaria.listarMedicos()){
            medico_consulta.addItem(medico.getNome());
        }
        
        medico_consulta.setSelectedItem(this.consulta.getMedico().getNome());

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoConsulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSubTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeSecretaria = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        data_consulta_label = new java.awt.Label();
        data_consulta = new javax.swing.JTextField();
        horario_consulta_label = new java.awt.Label();
        horario_consulta = new javax.swing.JTextField();
        normal = new javax.swing.JRadioButton();
        retorno = new javax.swing.JRadioButton();
        tipo_consulta_label = new java.awt.Label();
        paciente_consulta = new javax.swing.JComboBox<>();
        medico_consulta = new javax.swing.JComboBox<>();
        btn_Register = new javax.swing.JButton();
        lblMedico = new java.awt.Label();
        lblPaciente = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretária - Agendamento de consulta");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblSubTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitulo.setText("Agendar Consulta");
        lblSubTitulo.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuSecretariaConsulta(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Secretária:");

        lblNomeSecretaria.setBackground(new java.awt.Color(255, 255, 255));
        lblNomeSecretaria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeSecretaria.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeSecretaria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeSecretaria.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblNomeSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblNomeSecretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        data_consulta_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        data_consulta_label.setText("Data da consulta (dd/mm/aaaa):");

        data_consulta.setBackground(new java.awt.Color(255, 255, 255));
        data_consulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data_consulta.setForeground(new java.awt.Color(0, 0, 0));

        horario_consulta_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        horario_consulta_label.setText("Horario da consulta (hh:mm):");

        horario_consulta.setBackground(new java.awt.Color(255, 255, 255));
        horario_consulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horario_consulta.setForeground(new java.awt.Color(0, 0, 0));

        normal.setBackground(new java.awt.Color(204, 204, 204));
        tipoConsulta.add(normal);
        normal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        normal.setForeground(new java.awt.Color(0, 0, 0));
        normal.setText("Normal");

        retorno.setBackground(new java.awt.Color(204, 204, 204));
        tipoConsulta.add(retorno);
        retorno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        retorno.setForeground(new java.awt.Color(0, 0, 0));
        retorno.setText("Retorno");

        tipo_consulta_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo_consulta_label.setText("Tipo consulta:");

        paciente_consulta.setBackground(new java.awt.Color(255, 255, 255));
        paciente_consulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paciente_consulta.setForeground(new java.awt.Color(0, 0, 0));
        paciente_consulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o paciente", "Item 2", "Item 3", "Item 4" }));
        paciente_consulta.setToolTipText("");

        medico_consulta.setBackground(new java.awt.Color(255, 255, 255));
        medico_consulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medico_consulta.setForeground(new java.awt.Color(0, 0, 0));
        medico_consulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o medico", "Item 2", "Item 3", "Item 4" }));
        medico_consulta.setToolTipText("");

        btn_Register.setBackground(new java.awt.Color(51, 204, 0));
        btn_Register.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Register.setForeground(new java.awt.Color(255, 255, 255));
        btn_Register.setText("Cadastrar");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_cadAtuConsulta(evt);
            }
        });

        lblMedico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMedico.setText("Médico:");

        lblPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPaciente.setText("Paciente:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medico_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paciente_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horario_consulta_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data_consulta_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(data_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horario_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tipo_consulta_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(normal)
                        .addGap(41, 41, 41)
                        .addComponent(retorno))
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Register)
                .addGap(343, 343, 343))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(data_consulta_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_consulta))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horario_consulta_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo_consulta_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(normal)
                        .addComponent(retorno)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paciente_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medico_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(725, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Realiza o cadastro ou atualização da consulta, dependendo se uma consulta já foi fornecida.
     */
    private void go_cadAtuConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_cadAtuConsulta
        String nomeMedico_c, nomePaciente_c, tipo_c, horario_consulta_c, data_consulta_c;

        horario_consulta_c = horario_consulta.getText();
        data_consulta_c = data_consulta.getText();
        
        Medico medicoObj = null;
        Paciente pacienteObj  = null;
        
        if(normal.isSelected()){
            tipo_c = "NORMAL";
        }
        else{
            tipo_c = "RETORNO";
        }
        
        nomeMedico_c = (String) medico_consulta.getSelectedItem();
        nomePaciente_c = (String) paciente_consulta.getSelectedItem();
        
        
        if (!("Selecione um medico".equals(nomeMedico_c))) {
            // Busca o medico correspondente
            for (Medico medico : this.secretaria.listarMedicos()) {
                if (medico.getNome().equals(nomeMedico_c)) {
                    medicoObj = medico;
                    break;  // Encontre o medico e saia do loop

                }
            }
        }
        
        if (!("Selecione um paciente".equals(nomePaciente_c))) {
            // Busca o paciente correspondente
            for (Paciente paciente : this.secretaria.getAllPacientes()) {
                if (paciente.getNome().equals(nomePaciente_c)) {
                    pacienteObj = paciente;
                    break;  // Encontre o paciente e saia do loop

                }
            }
        }
        
        
        if(this.consulta == null){
            int dialogResult = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja agendar a consulta?",
                        "Confirmar Agendamento",
                        JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION){
                        this.secretaria.cadastrarConsulta(pacienteObj, medicoObj, LocalDate.parse(data_consulta_c, DateTimeFormatter.ofPattern("dd/MM/yyyy")), LocalTime.parse(horario_consulta_c, DateTimeFormatter.ofPattern("HH:mm")), tipo_c);
                        MenuSecretariaConsulta menuSecretariaConsulta = new MenuSecretariaConsulta(secretaria, gerenciadorAdm, em);
                        menuSecretariaConsulta.setVisible(true);
                        this.dispose();
                    }
        }else{
            int dialogResult = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja atualizar a consulta?",
                        "Confirmar Atualização",
                        JOptionPane.YES_NO_OPTION);
            
            if (dialogResult == JOptionPane.YES_OPTION){
                        this.secretaria.atualizarConsulta(this.consulta, pacienteObj, medicoObj, LocalDate.parse(data_consulta_c, DateTimeFormatter.ofPattern("dd/MM/yyyy")), LocalTime.parse(horario_consulta_c, DateTimeFormatter.ofPattern("HH:mm")), tipo_c);
                        MenuSecretariaConsulta menuSecretariaConsulta = new MenuSecretariaConsulta(secretaria, gerenciadorAdm, em);
                        menuSecretariaConsulta.setVisible(true);
                        this.dispose();
                    }
        }
    }//GEN-LAST:event_go_cadAtuConsulta

    private void backMenuSecretariaConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuSecretariaConsulta
        // TODO add your handling code here:
        MenuSecretariaConsulta menuSecretariaConsulta = new MenuSecretariaConsulta(secretaria, gerenciadorAdm, em);
        menuSecretariaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMenuSecretariaConsulta


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Register;
    private javax.swing.JTextField data_consulta;
    private java.awt.Label data_consulta_label;
    private javax.swing.JTextField horario_consulta;
    private java.awt.Label horario_consulta_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label lblMedico;
    private javax.swing.JLabel lblNomeSecretaria;
    private java.awt.Label lblPaciente;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JComboBox<String> medico_consulta;
    private javax.swing.JRadioButton normal;
    private javax.swing.JComboBox<String> paciente_consulta;
    private javax.swing.JRadioButton retorno;
    private javax.swing.ButtonGroup tipoConsulta;
    private java.awt.Label tipo_consulta_label;
    // End of variables declaration//GEN-END:variables
}